### ISSUE TITLE
Camera shakes when changing perspectives using F5 

### ISSUE THREAD

**Issue by aPersonIsHere** [Mirsario/Minecraft-CameraOverhaul#12]
I am using Java 15 and running on Fabric 1.16.5 and experience this issue.

How I'm Reproducing this Issue:

IMPORTANT: Make sure CameraOverhaul's setting "Enable the mod's effects" are set to "Yes". This issue will not occur when this variable is set to "No".
1.) When pressing F5, when I switch from the 1st-3rd person to the 2nd-3rd person view, it will cause the camera to shake.
2.) When pressing F5, when I switch from the 2nd-3rd person to the 1st person view, it will cause the camera to shake.

List of mods I'm using:
![image](https://user-images.githubusercontent.com/33707404/108606551-47a5fa00-7380-11eb-8eab-b2733da42821.png)
![image](https://user-images.githubusercontent.com/33707404/108606552-4b398100-7380-11eb-8631-ec97912e7d45.png)

**Comment by MopsTMC** [comment]
I can confirm this as well, tested this today with the following mods:
- BetterCaves-fabric-1.16.2-1.0.3.jar
- BetterMineshafts-Fabric-1.16.4-1.0.jar
- CameraOverhaul-1.2.2-fabric-universal.jar
- ChatEmotes-v1.1-Fabric-1.16.jar
- DynamicSoundFilters-1.2.0+1.16.5.jar
- FallingTree-Fabric-1.16.5-2.10.2.jar
- Mc122477Fix-fabric-mc1.16.jar
- Missing+Bits-v1.16.3+Fabric+b1.jar
- OfflineSkins-1.16.5-v1-fabric.jar
- PresenceFootsteps-r29+1.16.4.jar
- TRansliterationLib-1.0.2.jar
- YungsApi-1.16.4-Fabric-1.jar
- antiqueatlas-5.4.4-fabric.jar
- armor-visibility-1.0.1.jar
- atmosfera-1.3.5.jar
- autoconfig1u-3.3.1.jar
- bedspreads-fabric-1.3.1-1.16.4.jar
- beenfo-1.16.5-fabric0.30.0-1.3.jar
- better-end-0.9.1-pre.jar
- better-nether-5.0.7.jar
- betterf3-1.1.2+1.16.2.jar
- blame-1.16.4-2.4.1.jar
- chat_heads-0.2.1+1.16.2.jar
- cinderscapes-1.3.3.jar
- cloth-config-4.11.14-fabric.jar
- connectiblechains-1.1.0.jar
- cullleaves-2.0.0.jar
- custom-stars-0.4.1.jar
- dehydration-1.0.8.jar
- dynamic-fps-2.0.1.jar
- enhanced_attack_indicator-1.0.0+1.16.jar
- environmentz-1.0.10.jar
- fabric-api-0.30.3+1.16.jar
- fabric-language-kotlin-1.4.30+build.2.jar
- fabrishot-1.2.3.1.jar
- fallingleaves-1.5.0+1.16.5.jar
- fast-chest-1.0.jar
- hatlist-1.1.jar
- helpfulhitboxes-fabric-1.0.0.jar
- horse-stats-vanilla-4.1.4.jar
- howlingwolves-1.0.0+build.1.jar
- immersive-portals-0.78-mc1.16.5-fabric.jar
- item-model-fix-1.0.0.jar
- lambdynamiclights-fabric-1.3.4+1.16.jar
- lazydfu-0.1.2.jar
- lithium-fabric-mc1.16.5-0.6.3.jar
- microDurability-0.3.0+1.16.3.jar
- modmenu-1.16.7.jar
- nicephore-fabric-1.16.x-1.1.2.jar
- nostrip-1.2.0-1.16.2+.jar
- notenoughanimations-1.1.0.jar
- notenoughcrashes-3.1.5-fabric.jar
- now-playing-1.1.4-fat.jar
- okzoomer-4.0.1+1.16.2.jar
- onsoulfire-1.16.5-1.jar
- passable-leaves-1.2.3.jar
- phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
- pumice-0.0.2.jar
- randompatches-2.4.3-fabric.jar
- repurposed_structures-1.16.5-1.8.1.jar
- rocks-1.3.1.jar
- seamless-loading-screen-1.3.1+1.16.2.jar
- seasons-1.0.3-BETA.jar
- sheepconsistency-1.0.2.jar
- shulkerboxtooltip-2.3.5+1.16.5.jar
- signcopy-1.0.jar
- simple-utilities-mod-2.1.1.jar
- smoke-suppression-1.0+MC1.16.2-1.16.5.jar
- sodium-fabric-mc1.16.4-0.1.1-ipc2.jar
- splash-1.2.0.jar
- terrestria-2.2.0.jar
- tooltipfix-1.0.2-1.16.jar
- traverse-3.3.2.jar
- unearthed-1.1.0.jar
- vt-downloader-1.0.3.jar
- woodcutter-1.2-1.16.1.jar

**Comment by MopsTMC** [comment]
This is a similar issue with #11 and is a general incompatibility with mods.

**Comment by aPersonIsHere** [comment]
I am going to close this issue. While not the same case, the generality of #11 covers this issue.
