### ISSUE TITLE
1.17.1 crashing on launch

### ISSUE THREAD

**Issue by wojciechsacewicz** [Mirsario/Minecraft-CameraOverhaul#20]
Hey, I've got a crash on launch problem. 

The game does not launch after putting the mod into the mods folder.

Here are the logs that I know how to get.
https://hastebin.com/xagaqodevi.kotlin
https://hastebin.com/acicepapuj.yaml

If you need any more info please let me know where I can get it and I'll deliver it to you.

**Comment by Mirsario** [comment]
Fixed with #23 for [1.3.0](https://github.com/Mirsario/Minecraft-CameraOverhaul/releases/tag/1.3.0).
