### ISSUE TITLE
Incompatible with Fabric Loader 0.12

### ISSUE THREAD

**Issue by isuewo** [Mirsario/Minecraft-CameraOverhaul#21]
![Screenshot_20211008_175444](https://user-images.githubusercontent.com/53264315/136587223-94c079f1-f80c-4958-905f-aecda8befa8e.png)
![Screenshot_20211008_175638](https://user-images.githubusercontent.com/53264315/136587472-018b3771-77f4-4166-9d70-62671afacd8a.png)

I hope ^this explains everything

**Comment by VinnyStalck** [comment]
Here's an example of a [crash log](https://paste.ee/p/dBu6D) on `Fabric Loader 0.12.2` using `Camera Overhaul 1.2.2` and `Fabric API 0.41.0`

**Comment by Mirsario** [comment]
Fixed with #23 for [1.3.0](https://github.com/Mirsario/Minecraft-CameraOverhaul/releases/tag/1.3.0).
