### ISSUE TITLE
Incompatible with Iris

### ISSUE THREAD

**Issue by rbits0** [Mirsario/Minecraft-CameraOverhaul#24]
When Iris and Camera Overhaul are installed, the game crashes when trying to start.

**Comment by Mirsario** [comment]
I've used it with Iris and the experience was flawless. Post specific crashlogs (.minecraft/logs/latest.log after reproducing)

**Comment by rbits0** [comment]
[latest.log](https://github.com/Mirsario/Minecraft-CameraOverhaul/files/7449954/latest.log)
The only mods active are Iris/Sodium and Camera Overhaul. It works fine without Iris and with the latest Sodium.

**Comment by Mirsario** [comment]
The log contained nothing but warnings that are unrelated to this mod, sorry. I'm sure you'll be able to get it all working with newest versions of everything nowadays.
