### ISSUE TITLE
[Feature request] Additional camera effects

### ISSUE THREAD

**Issue by DB20-official** [Mirsario/Minecraft-CameraOverhaul#25]
If there are plans to expand the mod beyond just improving the satisfaction of basic movement, it'd be nice to see some additional effects, such as:
- [x] Slight camera movement when idle.
- [x] Camera shaking upon explosion.
- [ ] Enhanced view bobbing replacing vanilla view bobbing to be more realistic.
- And more if you have anymore ideas.

And if such features are implemented, have them fully configurable and toggleable. I never seen any Java mod bring actual camera shake asides from just doing teleportation commands to forcibly move the player's head to simulate camera shake.

This feedback was given when using:
Mod version: v1.3.0-fabric-universal
Minecraft version: 1.18

**Comment by ghost** [comment]
:0 very nice

**Comment by Mirsario** [comment]
Idle movement implemented in the above commit. CO 2.0 will be out soon:tm:.
