### ISSUE TITLE
Seemingly wrong version descriptions stop from including mod in curse-app modpack

### ISSUE THREAD

**Issue by Akorian** [Mirsario/Minecraft-CameraOverhaul#26]
I wanted to put all mods I use into a mod pack with the curseforge client. Problem is, that this mod works with 1.18.1, and even on the mod-homepage on curseforge is a version titled 1.18 But When inspecting the files in the files tab, no file has the 1.18 label. 
And because of this, it is impossible to put the mod into a mod pack using the curseforge client.

**Comment by Mirsario** [comment]
![image](https://user-images.githubusercontent.com/6795251/148680386-9ffb8d8f-e9be-454b-b7c8-6498c79f579c.png)
Ticked 1.18 & 1.18.1 now, thanks for telling me.
