### ISSUE TITLE
Update Camera Overhaul  to Minecraft 1.18.2

### ISSUE THREAD

**Issue by Celesian** [Mirsario/Minecraft-CameraOverhaul#28]
^ basically the title

**Comment by ghost** [comment]
yes we literally need 1.18.2 version plssssssssssssssssssssss

**Comment by DB20-official** [comment]
I have tested CameraOverhaul on 1.18.2, and it works just fine. There shouldn't be a need for a 1.18.2 version unless any incompatibilities I don't know of pop up. This isn't an official confirmation but just to let you know of this before the official response.

The video below shows proof of it working:
https://user-images.githubusercontent.com/26073967/165637318-8939e862-86b7-4bc9-be9b-59335bf768ba.mp4

**Comment by Mirsario** [comment]
Yes, it definitely works fine on all 1.18.X. And it loads on 1.19 too, except for ModMenu config screens being broken there.
If this was about curseforge builds not being marked with all the versions, it'll be fixed when I fix the config issue.
