### ISSUE TITLE
Incompatible with Quilt

### ISSUE THREAD

**Issue by Dakedres** [Mirsario/Minecraft-CameraOverhaul#30]
The newest version of CameraOverhaul crashes when you attempt to load it with Quilt

Crash log: https://paste.ee/p/sX2jh

I would really appreciate if this was fixed, thank you.

**Comment by Mirsario** [comment]
Been using internal/obsolete types that weren't part of any APIs, oops. I'll release a 1.3.1 with this soon.

**Comment by Dakedres** [comment]
Thank you! I've been missing this mod lol

**Comment by ahdg6** [comment]
> Been using internal/obsolete types that weren't part of any APIs, oops. I'll release a 1.3.1 with this soon.

Thank you for fixing this. Is there a release ETA for 1.3.1? Crash is a bit annoying.

**Comment by Mirsario** [comment]
@Dakedres @ahdg6 Sorry for the delays, [`1.3.1`](https://github.com/Mirsario/Minecraft-CameraOverhaul/releases) is now out with the fix in it.

**Comment by Dakedres** [comment]
Thank you!!
