### ISSUE TITLE
Update To 1.19

### ISSUE THREAD

**Issue by taciturnaxolotl** [Mirsario/Minecraft-CameraOverhaul#31]
This is a really great mod good work!!

**Comment by ghost** [comment]
DL for 1.19.x: https://github.com/Mirsario/Minecraft-CameraOverhaul/pull/32#issuecomment-1221186292

**Comment by Mirsario** [comment]
Resolved in 1.3.1 - https://github.com/Mirsario/Minecraft-CameraOverhaul/releases

**Comment by taciturnaxolotl** [comment]
Thank you for all your hard work. I really enjoy this mod!
