### ISSUE TITLE
MCO Not working with my Quilt / Fabric client modpack

### ISSUE THREAD

**Issue by Emnyczm** [Mirsario/Minecraft-CameraOverhaul#42]
**Hi!**

I cannot start the game, cuz it's crashing constantly without even opening Java / MC window. Quilt mod manager won't open as well.

Idk if that's an error, or just my modpack is incompatible (It's a massive client mod folder)

Using:

> CameraOverhaul-1.3.1-fabric-universal.jar

I think LamdaDynamicLights got someting to do with it 
**(have no Idea / not a programmer)** 

- Crash log:
- https://paste.ee/p/dE7Id

**Cheers!**

**Comment by Mirsario** [comment]
`cameraoverhaul                                | 1.3.1-fabric-universal `

Your mod version is out of date, `Do a Barrel Roll` does some injections into this mod, so make sure you're using latest versions of both of them.
