### ISSUE TITLE
Toggling perspective (F5) causes camera to shake 

### ISSUE THREAD

**Issue by nopeless** [Mirsario/Minecraft-CameraOverhaul#43]
Mods: 

- Camera Overhaul (1.4.0)
- Cloth config
- Mod Menu
- Quilted Fabric API

Reproduction: toggle perspective

I feel like this is a relatively easy fix. If this is somehow preventable by changing the config let me know

**Comment by peow** [comment]
can confirm in fabric 1.20.1

**Comment by Soabac** [comment]
happens in 1.21 too, it can get annoying sometimes
