### ISSUE TITLE
Modmenu fails to load CamOver config

### ISSUE THREAD

**Issue by minusHysteria** [Mirsario/Minecraft-CameraOverhaul#45]
![image](https://github.com/Mirsario/Minecraft-CameraOverhaul/assets/44898393/ff410914-d254-4788-abde-fe21212ba610)
Not sure what's causing this, it also happens even if I run no mods other than sodium family and common mods like IRIS
I'm running 1.20 on latest fabric.

**Comment by bobazix** [comment]
same problem in 1.19.4. But it crushes

**Comment by Mirsario** [comment]
What exact ModMenu, ClothConfig and CameraOverhaul's versions were used?

**Comment by bobazix** [comment]
> What exact ModMenu, ClothConfig and CameraOverhaul's versions were used?

I'm sorry, after i installed ClothConfig because i saw that CameraOverhaul need it, it started working.
