### ISSUE TITLE
Compatibility Report

### ISSUE THREAD

**Issue by MC-XiaoHei** [Mirsario/Minecraft-CameraOverhaul#46]
The latest release of this mod has been tested to work on 1.20

**Comment by Celesian** [comment]
config menu does not work on 1.20 though cc @Mirsario 

nevermind, just had cloth config issue

**Comment by MenacingPerson** [comment]
I can confirm that this does work. Please update metadata on modrinth. Thanks. @Mirsario

**Comment by Mirsario** [comment]
Updated it now, thanks for the reminders and sorry for the delay.
