### ISSUE TITLE
Incompatible with Lunar Client

### ISSUE THREAD

**Issue by Uri1x** [Mirsario/Minecraft-CameraOverhaul#48]
![image](https://github.com/Mirsario/Minecraft-CameraOverhaul/assets/88293215/da9a5c24-c229-49ea-9b33-5c26c03cb708)

**Comment by Uri1x** [comment]
Will we get an update to the mod? its one of if not my favorites.

**Comment by Uri1x** [comment]
will the mod be updated anymore? its one of if not my favorite mod.

**Comment by Mirsario** [comment]
Yes, I'll look into this when I'm able.

**Comment by Mirsario** [comment]
What dependency versions are you using? MC `1.20.4`, Cloth Config `13.0.0.121`, Mod Menu `9.0.0` - work just fine. If you're using latest ones (for your MC version) - provide a `latest.log` after trying to access the config.

I'm thinking of rewriting the mod using preprocessor conditionals, the "version agnostic" implementation created more pain than it did good to players.

**Comment by Uri1x** [comment]
I'm using Lunar Client MC 1.20.4, Cloth Config 13.0.0.121, Mod Menu 9.0.0, and the issue persists. I'll send the screenshot and the log, but also I believe this might be an incompatibility with lunarclient's modloading support given it's in its early stages with phase 2 only recently being announced.  Either way, I thank you for your help, and continued support of this mod. :)

![image](https://github.com/Mirsario/Minecraft-CameraOverhaul/assets/88293215/673dcaad-ab50-4315-9e55-1e7bc7ee82ba)

**Comment by Mirsario** [comment]
It seems like Lunar is a deobfuscated release, which is problematic for my reflection code, which feeds intermediary names (`net.minecraft.class_2561`) into a mapping resolver and tries to use reflection access on the output of that. I'm not sure whether it's my mod's dependencies or lunar that should be shipping mapping files to resolve this. I'll just pursue an alternative design for the mod that I mentioned in the previous message, hopefully I don't lazy out five minutes in.

(Also, be careful with hashes on GitHub, they mention issues & PRs and create notifications for people involved in those.)

**Comment by Uri1x** [comment]
The issue im certain is most likely on lunars end since this occurs with other mods, and it may possibly or hopefully be fixed in phase two of their release, but either way goodluck with the alternate design, and thank you for your hard work and for the heads up. 👍

**Comment by Mirsario** [comment]
Closing, v2.0 rewrite of CO has gotten rid of all reflection code that relies on the mapping resolver. Also yes, it was frankly Lunar's fault to begin with.
