### ISSUE TITLE
Port to older versions of Fabric

### ISSUE THREAD

**Issue by 726574726F** [Mirsario/Minecraft-CameraOverhaul#5]
Are you willing to port this mod to older versions of Fabric (ex. 1.15.2, 1.14.4)? People still use those and since Fabric seems to be more backwards compatible it should be possible (I have no idea though, I'm just a guy who wants to use mods and has no experience coding them).

**Comment by Mirsario** [comment]
The mod seems to work fine on 1.15 (and 1.17 snapshots!). 1.14 will need another mixin, though. I'll look into it.

**Comment by Mirsario** [comment]
Handled with 1.2.0.
