### ISSUE TITLE
Incompatible with Shoulder Surfing Reloaded

### ISSUE THREAD

**Issue by DziwnyPanPL** [Mirsario/Minecraft-CameraOverhaul#51]
### Description

Incompatible with [Shoulder Surfing Reloaded](https://modrinth.com/mod/shoulder-surfing-reloaded)

### Minecraft version

1.20.1 Fabric

### Incompatible mod name

Shoulder Surfing Reloaded

### Incompatible mod version

Camera Overhaul v1.4.0 / Shoulder Surfing 3.0.0

### Game Logs

https://mclo.gs/3kMIkam

**Comment by Mirsario** [comment]
The issue, whatever it was (upload logs to GitHub in the future), has seemingly been resolved from Shoulder Surfing's side at some point. With SSR v4.6.0 it happens with neither v1.4.0, v1.4.1, nor indev v2.0.0 of CO.
