### ISSUE TITLE
Do you have any predictions for the release of 1.20.6?

### ISSUE THREAD

**Issue by htaccexss** [Mirsario/Minecraft-CameraOverhaul#54]
I really like this mod, I miss it so much in the 1.20.6 that I'm currently playing, I would like to know if there is a release date for this version.

**Comment by AvacadoWizard120** [comment]
The Camera Mixin changed and I assume they're researching how they can do it in 1.20.6

**Comment by Mirsario** [comment]
v1.4.1 is now out with 1.20.6 and 1.21 both supported.

**Comment by htaccexss** [comment]
> v1.4.1 está agora fora com 1.20.6 e 1.21 ambos suportados. Minhas desculpas por isso levar tanto tempo - eu comecei um redesenho para um v2.0, mas deveria ter corrigido isso primeiro. O patch acabou sendo contribuído em vez disso.

Hey man, thanks a ton for updating your mod! Like I said before, I really enjoy it and was missing being able to play with it again. Your work on this mod is top-notch, great job on creating it. I wish you all the best and hope to see more of your work now for 1.21.
