### ISSUE TITLE
The screen will shake a little when the character falls. Can this effect be cancelled or disabled?

### ISSUE THREAD

**Issue by QianMuu** [Mirsario/Minecraft-CameraOverhaul#60]
https://github.com/user-attachments/assets/4e2f2364-8372-4839-9a2e-c3d0263b448e

Maybe using the original drop effect would be better,

Also, when you rotate the camera during flight, the picture will shake and not be smooth.

**Comment by Mirsario** [comment]
The `verticalVelocitySmoothingFactor` option should prevent this when set to default or something better. But the mod's current release is using incorrect delta-time values and is in need of a rewrite, which is kind of happening on the `dev` branch.
