### ISSUE TITLE
[fabric 1.21.1] Crash (incompatability?) when starting minecraft with camera overhaul installed.

### ISSUE THREAD

**Issue by cobaltlol2** [Mirsario/Minecraft-CameraOverhaul#63]
https://pastebin.com/2U41c7EG

**Comment by harpuppy** [comment]
same issue, seems like it might be caused by the latest update of do a barrel roll, version 3.7.1. no crash when using 3.6.2

**Comment by Mirsario** [comment]
Resolved by `Do A Barrel Roll`'s 3.7.2.
