### ISSUE TITLE
Change 1.21 to 1.21.x in supported versions of 1.4.1 on Modrinth and CurseForge

### ISSUE THREAD

**Issue by Poopooracoocoo** [Mirsario/Minecraft-CameraOverhaul#65]
1.21.1 was just a hotfix that fixed two bugs.

I briefly tested version 1.4.1 on MC 1.21.4 and it works well.

https://modrinth.com/mod/cameraoverhaul/version/1.4.1
https://www.curseforge.com/minecraft/mc-mods/cameraoverhaul/files/5441071

**Comment by Mirsario** [comment]
Done, thanks.
